export const mapUser = (u = {}) => ({
  id: u._id ?? u.id ?? "",
  fullName: u.fullName ?? "",
  email: u.email ?? "",
  phoneNumber: u.phoneNumber ?? "",
  gender: u.gender ?? "",
  dateOfBirth: u.dateOfBirth ?? null,
  nationalId: u.nationalId ?? "",
  address: u.address ?? "",
  city: u.city ?? "",
  emergencyContactName: u.emergencyContactName ?? "",
  emergencyContactPhone: u.emergencyContactPhone ?? "",
  role: u.role ?? "",
  isActive: u.isActive ?? true,
});

export const mapDoctor = (d = {}) => ({
  id: d._id ?? d.id ?? "",
  userId: typeof d.userId === "object" ? d.userId?._id ?? "" : d.userId ?? "",
  fullName: d.userId?.fullName ?? d.fullName ?? "Doctor",
  email: d.userId?.email ?? d.email ?? "",
  phoneNumber: d.userId?.phoneNumber ?? d.phoneNumber ?? "",
  registrationNumber: d.registrationNumber ?? "",
  specialization: d.specialization ?? "General Medicine",
  department: d.department ?? "General",
  qualifications: d.qualifications ?? [],
  yearsOfExperience: d.yearsOfExperience ?? 0,
  consultationFee: d.consultationFee ?? 0,
  biography: d.biography ?? "",
  languages: d.languages ?? [],
  availableDays: d.availableDays ?? [],
  workingHours: d.workingHours ?? { startTime:"", endTime:"" },
  slotDurationMinutes: d.slotDurationMinutes ?? 30,
  profileImage: d.profileImage ?? "",
  isActive: d.isActive ?? true,
});

export const mapAppointment = (a = {}) => ({
  id: a._id ?? a.id ?? "",
  doctorId: typeof a.doctorId === "object" ? a.doctorId?._id ?? "" : a.doctorId ?? "",
  patientId: typeof a.patientId === "object" ? a.patientId?._id ?? "" : a.patientId ?? "",
  doctor: typeof a.doctorId === "object" ? {
    id: a.doctorId?._id ?? "",
    fullName: a.doctorId?.userId?.fullName ?? "",
    specialization: a.doctorId?.specialization ?? "",
    department: a.doctorId?.department ?? "",
    consultationFee: a.doctorId?.consultationFee ?? null,
  } : null,
  patient: typeof a.patientId === "object" ? {
    id: a.patientId?._id ?? "",
    fullName: a.patientId?.fullName ?? "",
    email: a.patientId?.email ?? "",
    phoneNumber: a.patientId?.phoneNumber ?? "",
  } : null,
  appointmentDate: a.appointmentDate ?? null,
  appointmentStartTime: a.appointmentStartTime ?? "",
  durationMinutes: a.durationMinutes ?? 0,
  status: a.status ?? "pending",
  reason: a.reason ?? "",
  cancellationReason: a.cancellationReason ?? "",
});
