export const pageRegistry = [
  { id: "home", title: "Home", path: "/", role: "public", type: "mixed", showInNavigation: true },
  { id: "about", title: "About", path: "/about", role: "public", type: "static", showInNavigation: true },
  { id: "services", title: "Services", path: "/services", role: "public", type: "static", showInNavigation: true },
  { id: "departments", title: "Departments", path: "/departments", role: "public", type: "static", showInNavigation: true },
  { id: "doctors", title: "Doctors", path: "/doctors", role: "public", type: "dynamic", showInNavigation: true },
  { id: "doctor-details", title: "Doctor Details", path: "/doctors/:id", role: "public", type: "dynamic", showInNavigation: false },
  { id: "contact", title: "Contact", path: "/contact", role: "public", type: "static", showInNavigation: true },
  { id: "faq", title: "FAQ", path: "/faq", role: "public", type: "static", showInNavigation: false },
  { id: "privacy", title: "Privacy", path: "/privacy", role: "public", type: "static", showInNavigation: false },
  { id: "terms", title: "Terms", path: "/terms", role: "public", type: "static", showInNavigation: false },
  { id: "login", title: "Login", path: "/login", role: "public", type: "dynamic", showInNavigation: false },
  { id: "register", title: "Register", path: "/register", role: "public", type: "dynamic", showInNavigation: false },

  { id: "patient-dashboard", title: "Dashboard", path: "/patient/dashboard", role: "patient", type: "dynamic", showInNavigation: true },
  { id: "patient-doctors", title: "Find Doctors", path: "/patient/doctors", role: "patient", type: "dynamic", showInNavigation: true },
  { id: "patient-doctor-details", title: "Doctor Details", path: "/patient/doctors/:id", role: "patient", type: "dynamic", showInNavigation: false },
  { id: "patient-book", title: "Book Appointment", path: "/patient/appointments/book/:doctorId", role: "patient", type: "dynamic", showInNavigation: false },
  { id: "patient-appointments", title: "My Appointments", path: "/patient/appointments", role: "patient", type: "dynamic", showInNavigation: true },
  { id: "patient-appointment-details", title: "Appointment Details", path: "/patient/appointments/:id", role: "patient", type: "dynamic", showInNavigation: false },
  { id: "patient-profile", title: "Profile", path: "/patient/profile", role: "patient", type: "dynamic", showInNavigation: true },
  { id: "patient-password", title: "Change Password", path: "/patient/change-password", role: "patient", type: "dynamic", showInNavigation: true },

  { id: "doctor-dashboard", title: "Dashboard", path: "/doctor/dashboard", role: "doctor", type: "dynamic", showInNavigation: true },
  { id: "doctor-appointments", title: "Appointments", path: "/doctor/appointments", role: "doctor", type: "dynamic", showInNavigation: true },
  { id: "doctor-appointment-details", title: "Appointment Details", path: "/doctor/appointments/:id", role: "doctor", type: "dynamic", showInNavigation: false },
  { id: "doctor-profile", title: "Professional Profile", path: "/doctor/profile", role: "doctor", type: "dynamic", showInNavigation: true },
  { id: "doctor-availability", title: "Availability", path: "/doctor/availability", role: "doctor", type: "dynamic", showInNavigation: true },
  { id: "doctor-account", title: "Account", path: "/doctor/account", role: "doctor", type: "dynamic", showInNavigation: true },
  { id: "doctor-password", title: "Change Password", path: "/doctor/change-password", role: "doctor", type: "dynamic", showInNavigation: true },

  { id: "admin-dashboard", title: "Dashboard", path: "/admin/dashboard", role: "admin", type: "dynamic", showInNavigation: true },
  { id: "admin-users", title: "Users", path: "/admin/users", role: "admin", type: "dynamic", showInNavigation: true },
  { id: "admin-user-details", title: "User Details", path: "/admin/users/:id", role: "admin", type: "dynamic", showInNavigation: false },
  { id: "admin-doctors", title: "Doctors", path: "/admin/doctors", role: "admin", type: "dynamic", showInNavigation: true },
  { id: "admin-add-doctor", title: "Add Doctor", path: "/admin/doctors/new", role: "admin", type: "dynamic", showInNavigation: false },
  { id: "admin-doctor-details", title: "Doctor Details", path: "/admin/doctors/:id", role: "admin", type: "dynamic", showInNavigation: false },
  { id: "admin-edit-doctor", title: "Edit Doctor", path: "/admin/doctors/:id/edit", role: "admin", type: "dynamic", showInNavigation: false },
  { id: "admin-appointments", title: "Appointments", path: "/admin/appointments", role: "admin", type: "dynamic", showInNavigation: true },
  { id: "admin-appointment-details", title: "Appointment Details", path: "/admin/appointments/:id", role: "admin", type: "dynamic", showInNavigation: false },
  { id: "admin-profile", title: "Profile", path: "/admin/profile", role: "admin", type: "dynamic", showInNavigation: true },
  { id: "admin-password", title: "Change Password", path: "/admin/change-password", role: "admin", type: "dynamic", showInNavigation: true },

  { id: "unauthorized", title: "Unauthorized", path: "/403", role: "system", type: "static", showInNavigation: false },
  { id: "not-found", title: "Not Found", path: "*", role: "system", type: "static", showInNavigation: false },
];
